version: '3.8'

services:
  web:
    image: ghcr.io/elitealma/fidelizacion:latest
    container_name: fidelizacion-web
    restart: always
    networks:
      - pegasus_net
    labels:
      # Habilitar Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=pegasus_net"

      # Router para HTTP (redirige a HTTPS)
      - "traefik.http.routers.fidelizacion.rule=Host(`fidelizacion.pegasus360agency.com`)"
      - "traefik.http.routers.fidelizacion.entrypoints=web"
      - "traefik.http.routers.fidelizacion.middlewares=redirect-to-https"

      # Router para HTTPS
      - "traefik.http.routers.fidelizacion-secure.rule=Host(`fidelizacion.pegasus360agency.com`)"
      - "traefik.http.routers.fidelizacion-secure.entrypoints=websecure"
      - "traefik.http.routers.fidelizacion-secure.tls.certresolver=letsencryptresolver"

      # Servicio
      - "traefik.http.services.fidelizacion.loadbalancer.server.port=80"

      # Middleware de redirección HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"


networks:
  pegasus_net:
    external: true

